/**
 * UI Message Chunk Types - AI SDK v6 Compatibility Layer
 *
 * This module provides type definitions for streaming message chunks compatible with
 * AI SDK v6's useChat hook. It re-exports the base UIMessageChunk type and defines
 * specific chunk types used in SSE and BIDI streaming responses.
 *
 * Purpose:
 * - Provide type-safe chunk handling for streaming responses
 * - Support both text streaming and tool execution workflows
 * - Enable tool confirmation (approval) in ADK protocol modes
 *
 * Used By:
 * - lib/sse/transport.ts: SSE streaming response processing
 * - lib/bidi/transport.ts: WebSocket bidirectional streaming
 * - lib/chunk_logs/: Chunk logging and replay system
 *
 * Chunk Flow in Streaming:
 * 1. Text chunks: START → DELTA (multiple) → END
 * 2. Tool chunks: INPUT_START → INPUT_AVAILABLE → APPROVAL_REQUEST (ADK modes only)
 */

// Re-export AI SDK v6 base chunk type for external use
export type { UIMessageChunk } from "ai";

// Import constants for type definitions
import type {
  TEXT_CHUNK_TYPE_DELTA,
  TEXT_CHUNK_TYPE_END,
  TEXT_CHUNK_TYPE_START,
  TOOL_CHUNK_TYPE_APPROVAL_REQUEST,
  TOOL_CHUNK_TYPE_INPUT_AVAILABLE,
  TOOL_CHUNK_TYPE_INPUT_START,
} from "../constants";

// SSE/BIDI specific chunk types (based on AI SDK v6 UIMessageChunk structure)

/**
 * Text Start Chunk
 *
 * Signals the beginning of a new text response stream. This is the first chunk
 * sent when the AI starts generating a text response. The frontend typically uses
 * this to initialize UI elements for displaying the streaming text.
 *
 * @property type - Chunk type identifier (constant: "text-start")
 * @property id - Unique identifier for this text stream segment
 */
export interface TextStartChunk {
  type: typeof TEXT_CHUNK_TYPE_START;
  id: string;
}

/**
 * Text Delta Chunk
 *
 * Contains incremental text content as it's generated by the AI. Multiple delta
 * chunks are sent in sequence to stream the complete response. The frontend appends
 * each delta to the displayed text to create a real-time typing effect.
 *
 * @property type - Chunk type identifier (constant: "text-delta")
 * @property delta - Incremental text content to append to the response
 * @property id - Unique identifier matching the corresponding START chunk
 */
export interface TextDeltaChunk {
  type: typeof TEXT_CHUNK_TYPE_DELTA;
  delta: string;
  id: string;
}

/**
 * Text End Chunk
 *
 * Signals the completion of a text response stream. This is the final chunk for
 * a text segment, indicating that no more delta chunks will follow. The frontend
 * uses this to finalize UI state and enable user interaction.
 *
 * @property type - Chunk type identifier (constant: "text-end")
 * @property id - Unique identifier matching the corresponding START chunk
 */
export interface TextEndChunk {
  type: typeof TEXT_CHUNK_TYPE_END;
  id: string;
}

/**
 * Tool Input Start Chunk
 *
 * Signals the beginning of a tool call input stream. This chunk is sent when the AI
 * decides to invoke a tool and starts sending the tool parameters. The frontend uses
 * this to initialize tool execution UI or logging.
 *
 * @property type - Chunk type identifier (constant: "tool-input-start")
 * @property toolCallId - Unique identifier for this specific tool invocation
 * @property toolName - Name of the tool being invoked (e.g., "search", "get_location")
 */
export interface ToolInputStartChunk {
  type: typeof TOOL_CHUNK_TYPE_INPUT_START;
  toolCallId: string;
  toolName: string;
}

/**
 * Tool Input Available Chunk
 *
 * Contains the complete tool invocation parameters after they have been fully streamed.
 * This chunk indicates that all tool arguments are available and ready for execution
 * or approval. In ADK modes, this triggers the approval request flow.
 *
 * @property type - Chunk type identifier (constant: "tool-input-available")
 * @property toolCallId - Unique identifier matching the corresponding START chunk
 * @property toolName - Name of the tool with complete input parameters
 * @property input - Complete tool parameters (structure varies by tool)
 */
export interface ToolInputAvailableChunk {
  type: typeof TOOL_CHUNK_TYPE_INPUT_AVAILABLE;
  toolCallId: string;
  toolName: string;
  input: unknown;
}

/**
 * Tool Approval Request Chunk
 *
 * Requests user confirmation before executing a tool (ADK protocol specific).
 * This chunk is only sent in adk-sse and adk-bidi modes when the backend requires
 * explicit user approval before tool execution. The frontend presents a confirmation
 * UI and sends the approval response via addToolApprovalResponse().
 *
 * Note: Not used in gemini mode (direct execution without confirmation).
 *
 * @property type - Chunk type identifier (constant: "tool-approval-request")
 * @property approvalId - Unique identifier for tracking this approval request
 * @property toolCallId - Tool call ID this approval request is for
 */
export interface ToolApprovalRequestChunk {
  type: typeof TOOL_CHUNK_TYPE_APPROVAL_REQUEST;
  approvalId: string;
  toolCallId: string;
}

/**
 * SSE Stream Chunk Union Type
 *
 * Covers the most common chunk types used in SSE and BIDI streaming responses.
 * This type provides type-safe handling of all chunk variants that can appear
 * in the streaming data flow.
 *
 * Used For:
 * - Type guards in transport layers (lib/sse/transport.ts, lib/bidi/transport.ts)
 * - Chunk processing and transformation
 * - Chunk logging and replay (lib/chunk_logs/)
 *
 * Chunk Categories:
 * - Text chunks: TextStartChunk, TextDeltaChunk, TextEndChunk
 * - Tool chunks: ToolInputStartChunk, ToolInputAvailableChunk, ToolApprovalRequestChunk
 *
 * Note: This union type does not include all possible AI SDK v6 chunk types
 * (e.g., error chunks, custom chunks). Use UIMessageChunk for complete coverage.
 */
export type SseChunk =
  | TextStartChunk
  | TextDeltaChunk
  | TextEndChunk
  | ToolInputStartChunk
  | ToolInputAvailableChunk
  | ToolApprovalRequestChunk;
