/**
 * Integration Test: approval.id vs toolCallId Distinction (ADR 0002)
 *
 * This test documents a critical distinction in the AI SDK v6 approval API:
 *
 * WRONG ❌:
 * ```typescript
 * addToolApprovalResponse({
 *   id: part.toolCallId,  // ← WRONG! This is the tool's ID
 *   approved: true,
 * });
 * // Result: Nothing happens, state stays "approval-requested"
 * ```
 *
 * CORRECT ✅:
 * ```typescript
 * addToolApprovalResponse({
 *   id: part.approval.id,  // ← CORRECT! Use approval.id
 *   approved: true,
 * });
 * // Result: State changes to "approval-responded" immediately
 * ```
 *
 * Why they are different:
 * - toolCallId: The ID of the tool call itself (e.g., "orig-payment-123")
 * - approval.id: The ID of the approval request (e.g., "approval-abc-456")
 * - These are SEPARATE values generated by the backend
 * - Only approval.id will trigger state transition in AI SDK
 *
 * Reference: agents/my-understanding.md lines 289-304
 *
 * @vitest-environment jsdom
 */

import { useChat } from "@ai-sdk/react";
import { act, renderHook, waitFor } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { buildUseChatOptions } from "../../bidi";
import { useMockWebSocket } from "../helpers/mock-websocket";

describe("ADR 0002: approval.id vs toolCallId Distinction", () => {
  const { setDefaultHandler } = useMockWebSocket();

  // Common handler factory for sending approval request
  const createApprovalHandler = (toolCallId: string, approvalId: string) => {
    return (ws: import("../helpers/mock-websocket").BidiMockWebSocket) => {
      ws.onClientMessage((data) => {
        if (!data.startsWith("{")) {
          return;
        }

        const msg = JSON.parse(data);

        if (
          msg.type === "message" &&
          msg.messages &&
          !msg.messages[msg.messages.length - 1].parts?.some(
            (p: any) => p.type === "tool-process_payment",
          )
        ) {
          console.log(
            `[Test] Sending approval with toolCallId="${toolCallId}" and approvalId="${approvalId}"`,
          );

          ws.simulateServerMessage({ type: "start", messageId: "msg-1" });
          ws.simulateServerMessage({
            type: "tool-input-start",
            toolCallId,
            toolName: "process_payment",
          });
          ws.simulateServerMessage({
            type: "tool-input-available",
            toolCallId,
            toolName: "process_payment",
            input: { amount: 30, recipient: "Alice", currency: "USD" },
          });
          ws.simulateServerMessage({
            type: "tool-approval-request",
            toolCallId,
            approvalId,
          });
          ws.simulateServerMessage({ type: "finish-step" });
          ws.simulateDone();
        }
      });
    };
  };

  it("demonstrates toolCallId vs approval.id are DIFFERENT values", async () => {
    // Given: Backend sends approval request with DISTINCT IDs
    const TOOL_CALL_ID = "orig-payment-123"; // ← Tool call ID
    const APPROVAL_ID = "approval-abc-456"; // ← Approval request ID

    setDefaultHandler(createApprovalHandler(TOOL_CALL_ID, APPROVAL_ID));

    const { useChatOptions } = buildUseChatOptions({
      initialMessages: [],
      adkBackendUrl: "http://localhost:8000",
      forceNewInstance: true,
    });

    const { result } = renderHook(() => useChat(useChatOptions));

    // When: Send message
    await act(async () => {
      result.current.sendMessage({ text: "Send $30 to Alice" });
    });

    // Then: Wait for approval request
    await waitFor(
      () => {
        const lastMsg =
          result.current.messages[result.current.messages.length - 1];
        const tool = lastMsg?.parts?.find(
          (p: any) => p.type === "tool-process_payment",
        );
        return tool?.state === "approval-requested";
      },
      { timeout: 5000 },
    );

    // Verify: Tool part has BOTH IDs
    const lastMsg = result.current.messages[result.current.messages.length - 1];
    const tool = lastMsg?.parts?.find(
      (p: any) => p.type === "tool-process_payment",
    );

    expect(tool?.toolCallId).toBe(TOOL_CALL_ID); // ← Tool ID
    expect(tool?.approval?.id).toBe(APPROVAL_ID); // ← Approval ID
    expect(tool?.toolCallId).not.toBe(tool?.approval?.id); // ← DIFFERENT!

    console.log(`✓ toolCallId: "${tool?.toolCallId}"`);
    console.log(`✓ approval.id: "${tool?.approval?.id}"`);
    console.log("✓ These are DISTINCT values!");
  });

  it("WRONG: Using toolCallId does NOT change state", async () => {
    // Given: Backend sends approval request
    const TOOL_CALL_ID = "orig-payment-123";
    const APPROVAL_ID = "approval-abc-456";

    setDefaultHandler(createApprovalHandler(TOOL_CALL_ID, APPROVAL_ID));

    const { useChatOptions } = buildUseChatOptions({
      initialMessages: [],
      adkBackendUrl: "http://localhost:8000",
      forceNewInstance: true,
    });

    const { result } = renderHook(() => useChat(useChatOptions));

    await act(async () => {
      result.current.sendMessage({ text: "Send $30 to Alice" });
    });

    await waitFor(
      () => {
        const lastMsg =
          result.current.messages[result.current.messages.length - 1];
        const tool = lastMsg?.parts?.find(
          (p: any) => p.type === "tool-process_payment",
        );
        return tool?.state === "approval-requested";
      },
      { timeout: 5000 },
    );

    // When: Use WRONG ID (toolCallId instead of approval.id)
    const lastMsg = result.current.messages[result.current.messages.length - 1];
    const tool = lastMsg?.parts?.find(
      (p: any) => p.type === "tool-process_payment",
    );

    console.log("❌ Using WRONG ID: toolCallId instead of approval.id");

    await act(async () => {
      result.current.addToolApprovalResponse({
        id: tool?.toolCallId, // ← WRONG! Using tool ID instead of approval ID
        approved: true,
      });
    });

    // Then: State should NOT change (stays "approval-requested")
    const currentMsg =
      result.current.messages[result.current.messages.length - 1];
    const currentTool = currentMsg?.parts?.find(
      (p: any) => p.type === "tool-process_payment",
    );

    expect(currentTool?.state).toBe("approval-requested"); // ← Still waiting!
    expect(currentTool?.approval?.approved).toBeUndefined(); // ← Not approved

    console.log("✓ State remained 'approval-requested' (not changed)");
    console.log("✓ This demonstrates why toolCallId is WRONG");
  });

  it("CORRECT: Using approval.id changes state immediately", async () => {
    // Given: Backend sends approval request
    const TOOL_CALL_ID = "orig-payment-123";
    const APPROVAL_ID = "approval-abc-456";

    setDefaultHandler(createApprovalHandler(TOOL_CALL_ID, APPROVAL_ID));

    const { useChatOptions } = buildUseChatOptions({
      initialMessages: [],
      adkBackendUrl: "http://localhost:8000",
      forceNewInstance: true,
    });

    const { result } = renderHook(() => useChat(useChatOptions));

    await act(async () => {
      result.current.sendMessage({ text: "Send $30 to Alice" });
    });

    await waitFor(
      () => {
        const lastMsg =
          result.current.messages[result.current.messages.length - 1];
        const tool = lastMsg?.parts?.find(
          (p: any) => p.type === "tool-process_payment",
        );
        return tool?.state === "approval-requested";
      },
      { timeout: 5000 },
    );

    // When: Use CORRECT ID (approval.id)
    const lastMsg = result.current.messages[result.current.messages.length - 1];
    const tool = lastMsg?.parts?.find(
      (p: any) => p.type === "tool-process_payment",
    );

    console.log("✅ Using CORRECT ID: approval.id");

    await act(async () => {
      result.current.addToolApprovalResponse({
        id: tool?.approval?.id, // ← CORRECT! Using approval ID
        approved: true,
      });
    });

    // Then: State DOES change to "approval-responded"
    const currentMsg =
      result.current.messages[result.current.messages.length - 1];
    const currentTool = currentMsg?.parts?.find(
      (p: any) => p.type === "tool-process_payment",
    );

    expect(currentTool?.state).toBe("approval-responded"); // ← Changed!
    expect(currentTool?.approval?.approved).toBe(true); // ← Approved

    console.log("✓ State changed to 'approval-responded' immediately");
    console.log("✓ approval.approved = true");
    console.log("✓ This demonstrates why approval.id is CORRECT");
  });

  it("Summary: Always use approval.id, never toolCallId", () => {
    /**
     * KEY TAKEAWAY:
     *
     * ❌ WRONG:
     * addToolApprovalResponse({ id: part.toolCallId, ... })
     * Result: No state change, approval ignored
     *
     * ✅ CORRECT:
     * addToolApprovalResponse({ id: part.approval.id, ... })
     * Result: State → "approval-responded", approval.approved = true
     *
     * Why:
     * - toolCallId: Identifies the tool call ("orig-payment-123")
     * - approval.id: Identifies the approval request ("approval-abc-456")
     * - AI SDK v6 uses approval.id to match approval responses
     * - Using toolCallId will silently fail (no error, just ignored)
     *
     * Reference:
     * - agents/my-understanding.md lines 289-304
     * - AI SDK v6 documentation
     * - ADR 0002: Tool Approval Architecture
     */
    expect(true).toBe(true); // Documentation test
  });
});
